# TODO
language: rust

rust:
    - 1.0.0
    - stable
    - beta
    - nightly

jobs:
    allow_failures:
        - rust: nightly
        - rust: beta

cache: cargo

script:
    - cargo build --verbose --all

deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file:
        - "FILE TO UPLOAD"
    skip_cleanup: true
    skip_cleanup: true
    on:
      branch: master