[package]
name = "gotham"
version = "0.0.1"
authors = ["Rakshith Ravi <rakshith.ravi@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
async-std = "1.4.0"
lazy_static = "1.4.0"
serde_json = "1.0.44"
futures = "0.3.1"
futures-util = "0.3.1"
uuid = "0.8.1"
rand = "0.7.2"
file-lock = "1.1.20"
ctrlc = "3.1.3"
semver = "0.9.0"
