on:
  pull_request:
    branches:
      - master
name: New Release Version Check
jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Release Version
        uses: thebongy/version-check@v1
        with:
          file: Cargo.toml
        id: version_check
